# Generated by Django 4.2.2 on 2023-06-14 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('time', models.IntegerField(choices=[('10', '10'), ('3', '3')], null=True)),
                ('room_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.room')),
            ],
        ),
    ]
