# Generated by Django 4.2.2 on 2023-06-20 08:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_booking_checkin_alter_booking_checkout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='room_no',
            new_name='room',
        ),
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
