# Generated by Django 4.2.2 on 2023-06-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_booking_date_alter_booking_checkin_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(check=models.Q(('checkin__lte', models.F('checkout')), ('checkout__gte', models.F('checkin')), ('room', models.F('room'))), name='booking'),
        ),
    ]
